name: default
desc: for other gyros
profile:
  filter:
    gyro:
      - type: 2
        cutoff_freq: 100
      - type: 0
        cutoff_freq: 90
    dterm:
      - type: 1
        cutoff_freq: 260
      - type: 0
        cutoff_freq: 0
    dterm_dynamic_enable: 1
    dterm_dynamic_min: 70
    dterm_dynamic_max: 260
  pid:
    pid_profile: 0
    pid_rates:
      - kp:
          - 117
          - 117
          - 150
        ki:
          - 77
          - 77
          - 77
        kd:
          - 41
          - 41
          - 11
      - kp:
          - 130
          - 130
          - 140
        ki:
          - 77
          - 77
          - 77
        kd:
          - 42
          - 42
          - 11
